name: hw_reader
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  tflite: ^1.1.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  flutter_screenutil: ^5.6.0
  flutter_native_image: ^0.0.6+1
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/tfiles/
    - assets/fonts/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico.ttf
    - family: Chakra
      fonts:
        - asset: assets/fonts/chakra.ttf